[site]
title = "Xiaohei Terminal"
subtitle = "Xiaohei's blog"
author = "Xiaohei"
copyright_year = "2022-2023"
timezone = "Asia/Shanghai"
language = "zh-Hans"

[config]
posts_per_index_page = 20
disqus_enabled = true
disqus_short_name = "xiaohei-terminal"
hitokoto_enabled = true
hitokoto_categories = ["a", "d", "i", "k"]
