name: purepress-deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Build website
        run: |
          echo "https://xiaohei.moe" | poetry run purepress build
        working-directory: "./"

      - name: Upload build folder to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./build"
          cname: "xiaohei.moe"
